CREATE DATABASE IF NOT EXISTS mrp;

USE mrp;

DROP TABLE IF EXISTS mrp_products;

CREATE TABLE mrp_products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product VARCHAR(50) NOT NULL,
    component VARCHAR(50) NOT NULL UNIQUE KEY,
    quantity INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;

ALTER DATABASE mrp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;